### ISSUE TITLE
Back image

### ISSUE THREAD

**Issue by umpirsky** [umpirsky/tilda.rs#14]
http://anglehtml.oxygenna.com/background-images.html

**Comment by umpirsky** [comment]
@tosovic Naša slika je 2048 x 669, i zato se javlja ovaj problem:

![selection_001](https://cloud.githubusercontent.com/assets/208957/6768751/453e73b0-d07e-11e4-8a77-e8bf8893aafb.png)

Slka koja je korišćena u temi je 1280 x 649.

Dakle možemo da idemo sa većom rezolucijom, ali aspect ratio treba da bude isti, ili bar približan. U temi je 1.97, kod nas 3.06.

**Comment by tosovic** [comment]
- Promenio velicinu slike na 1280x649 i repozicionirao tako da se vide stolovi i stolice, a ne plafon.
- Ne radi kako treba sa svim velicinama ekrana, ali na identican nacin se ponasa i njihov primer, tako da je najverovatnije do js.
- Radi kako treba u full screen na >13" ekranima sto je po meni dovoljno dobro
- Promene mozete da vidite na grani fix/issue-14-4

**Comment by umpirsky** [comment]
@tosovic Sad je bolje, hvala.

Kod nas je problem što imamo nešto više sadržaja na ovoj strani od njih (paragraf "Prvi coworking prostor u Nišu") pa je problem zato izraženiji.

Mislim da je ovo dovoljno dobro, samo treba sliku da prebacimo na fb zbog bržeg učitavanja i to je to.

**Comment by umpirsky** [comment]
Ispravljeno u https://github.com/umpirsky/tilda.rs/pull/40.
