### ISSUE TITLE
FB reklama ready

### ISSUE THREAD

**Issue by umpirsky** [umpirsky/tilda.rs#41]
- Ukloni sekciju "O nama".
- Zameni je sekcijom "Startuj besplatno" sa sledećom sadržinom:

`Svi novi članovi imaju priliku da besplatno isprobaju naš prostor. Prva nedelja se ne naplaćuje i to je period koji možete iskoristiti da se uverite da je Tilda idealno mesto za rad. Kontaktirajte nas još danas i besplatno rezervišite svoje mesto u modernoj kancelariji u centru grada.`
- U ovoj sekciji dodati i slike prostora sa ljudima (čekamo Srđana da pošalje slike). 
- U sekciji "Cene" zameni "Prvi dolazak se ne naplaćuje!" tekstom "Prvi nedeljni paket se ne naplaćuje!".

**Comment by tosovic** [comment]
- "uverite da je Tilda idealno mesto za rad" -> pre bih nesto u stilu: "da proverite da li vam Tilda odgovara"
- mislim da u sekciji cene treba da postoji jos jedan paket cija ce cena biti "free". sam tekst "Prvi nedeljni paket se ne naplaćuje!", velicine 14px, koji se nalazi ispod sekcije sa paketima je maltene nevidljiv.

**Comment by draganjovev** [comment]
![photo 26 5 15 19 33 40](https://cloud.githubusercontent.com/assets/1249789/10136905/3912fafc-65f7-11e5-9089-c472426fcded.jpg)
![photo 26 5 15 19 33 31](https://cloud.githubusercontent.com/assets/1249789/10136903/3911fc60-65f7-11e5-81c6-a5417de2d559.jpg)
![photo 26 5 15 19 10 47](https://cloud.githubusercontent.com/assets/1249789/10136902/3910f586-65f7-11e5-80ce-9e7d9f964268.jpg)
![photo 21 9 15 18 09 15](https://cloud.githubusercontent.com/assets/1249789/10136904/39126984-65f7-11e5-9be3-a6069a3b3e5a.jpg)
![photo 21 9 15 18 05 35](https://cloud.githubusercontent.com/assets/1249789/10136901/39104eb0-65f7-11e5-8be0-095472630d79.jpg)

**Comment by umpirsky** [comment]
@draganjovev Šta misliš o tekstu i [Saletovim predlozima](https://github.com/umpirsky/tilda.rs/issues/41#issuecomment-143745355)?

**Comment by draganjovev** [comment]
@umpirsky @tosovic slozio sam se odmah ali nisam napisao. Sto se mene tice sve usvajamo.

**Comment by umpirsky** [comment]
Prvi korak vezan za besplatni paket je na https://github.com/umpirsky/tilda.rs/pull/42.

@tosovic @draganjovev Pogledajte pa da to prvo rešimo.

**Comment by umpirsky** [comment]
Startuj besplatno PR https://github.com/umpirsky/tilda.rs/pull/44.

@tosovic @draganjovev Pogledajte kad imate vremena da rešimo ovaj issue 41.
